config/routes.rb
Rails.application.routes.draw do

  get 'show_user' => 'epicenter#show_user'
  get 'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollow'
  get 'tag_tweets' => 'epicenter#tag_tweets'
  get 'all_users' => 'epicenter#all_users'
  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'

  resources :tweets
  devise_for :users

  root 'epicenter#feed'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tweet_tags
  has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :tweet_tags
  has_many :tags, through: :tweet_tags

  before_validation :link_check, on: :create

  validates :message, presence: true
  validates :message, length: {maximum: 140, too_long: "A tweet is only 140 max. Everybody knows that!"}, on: :create

  after_validation :apply_link, on: :create


  private

  def apply_link
    arr = self.message.split
    index = arr.map { |x| x.include? "http://" }.index(true)
    if index
		  url = arr[index]
		  arr[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
	  end

	  self.message = arr.join(" ")
  end

  def link_check
    check = false
    if message.include?('http://') || message.include?('https://')
    check = true
    end

    if check
      arr = self.message.split
      index = arr.map { |word| word.include?('http')}.index(true)
      self.link = arr[index]
      if arr[index].length > 23
        arr[index] = "#{arr[index][0..20]}..."
      end

      self.message = arr.join(" ")
    end
  end
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
  belongs_to :tweet
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :tweets

mount_uploader :avatar, AvatarUploader

serialize :following, Array

validates :username, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar, :following])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar, :following])
  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController

  before_action :set_user, only: [:show_user, :following, :followers, :feed]

  def feed
    following_user_ids = current_user.following + [current_user.id]
    @following_tweets = Tweet.where(user_id: following_user_ids)
    @tweet = Tweet.new

  end

  def show_user

  end

  def now_following
    current_user.update(following: current_user.following.push(params[:id].to_i))

    redirect_to show_user_path(id: params[:id])
  end

  def unfollow
    current_user.update(following: current_user.following.delete(params[:id].to_i))
    redirect_to show_user_path(id: params[:id])
  end

  def tag_tweets
    @tag = Tag.find(params[:id])
  end

  def all_users
    @users = User.all
    # or:
    # User.order(:username)
    # User.order(:name)
    # or whatever order you'd
    # like to put them in
  end

  def following
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @users.push(user)
      end
    end
  end

  def followers
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if user.following.include?(@user.id)
        @users.push(user)
      end
    end
  end

  def set_user
    @user = User.find(params[:id] || current_user.id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)

    message_arr = @tweet.message.split

    message_arr.each_with_index do |word, index|
      if word[0] == '#'
        if Tag.pluck(:phrase).include?(word)
          #save tag as a variable and create TweetTag
          tag = Tag.find_by(phrase: word)
        else
          #tag doesn't exist, make new tag and new tweet_tag
          tag = Tag.create(phrase: word)
        end
        tweet_tag = TweetTag.create(tag_id: tag.id, tweet_id:@tweet.id)
        message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
      end
    end

    @tweet.update(message: message_arr.join(" "))

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to :root, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { redirect_to :root, tweet: @tweet }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/epicenter/_user_list.html.erb
<ul class="list-group">
  <% @users.each do |user| %>
  <li class="list-group-item">


    <div class="media">
      <div class="media-left">
        <%= image_tag user.avatar.url, class:"img-circle", height: "60px", width:"60px" %>

      </div>
      <div class="media-body">
        <%= link_to show_user_path(id: user.id) do %>
        <h3 class="media-heading"><%= user.name %></h3>
        <p>@<%= user.username %></p>
        <p>
          <% if current_user.following.include?(user.id) %>
          <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary", id: "unfollow_btn" %>
          <% else %>
          <% if current_user.id != user.id %>
          <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
          <% end %>
          <% end %>

          <% end %>
        </p>
        <p><%= user.bio %></p>
      </div>
    </li>

    <% end %>
  </ul>

app/views/epicenter/all_users.html.erb
<%= render 'user_list' %>

app/views/epicenter/feed.html.erb
<div class="container">
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
    <div id="homeprofile">

        <h4><%= image_tag current_user.avatar.url, id:"homeprofilepic", class:"img-circle", width:"60px", height:"60px" %> <%= current_user.name %></h4>
        <h6>@<%= current_user.username %></h6>

        <table id="profiletable">
          <tr>
            <th><small>Tweets</small></td>
            <th><small>Following</small><td>
            <th><small>Followers</small><td>
              </tr>
              <tr>
                <td><%= current_user.tweets.count %></td>
                <td><%= current_user.following.count %></td>
                <td><% @users = [] %>

                  <% User.all.each do |user| %>
                  <% if user.following.include?(current_user.id) %>
                  <% @users.push(user) %>
                  <% end %>
                  <% end %>
                  <%= @users.count %></td>
                </tr>
              </table>
    </div>
<div>
  <h4>Who to Follow:</h4>
  <% @users = User.all %>

  <%= render 'user_list' %>
</div>
</div>

<div class="container col-xs-9 col-sm-9 col-md-9 col-lg-9">
  <div id="new_form" class="well">
    <%= render 'tweets/form', tweet: @tweet %>
  </div>
<div>
  <ul class="list-group">

    <%= render @following_tweets.reverse %>
</ul>
</div>
</div>

app/views/epicenter/followers.html.erb
<h2><%= @user.name %>'s Followers:</h2>
<%= render 'user_list' %>

app/views/epicenter/following.html.erb
<h2><%= @user.name %> is following:</h2>
<%= render 'user_list' %>

app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<!-- Needs a jumbotron with the avatar and the who they're following info plus the side bar with the bio and location, etc -->
<div id="bluejumbo" class="jumbotron-fluid">
</div>
<div id="whitejumbo" class="jumbotron-fluid">
  <div class="col-lg-3 col-md-3 col-s-3 col-xs-3">
        <img class="img-responsive" id="main_pic"><%= image_tag @user.avatar.url, class:"img-circle", width:"120px", height:"120px" %></img>
  </div>
  <div class="col-lg-1 col-md-1 col-s-2 col-xs-2">
      <h5 id="header" class="text-center">Tweets</h5>
      <p id="header" class="text-center"><%= @user.tweets.count %></p>
    </div>
    <div class="col-lg-1 col-md-2 col-s-2 col-xs-2">
        <h5 id="header" class="text-center">Following</h5>
        <p id="header" class="text-center"><%= @user.following.count %></p>
      </div>
      <div class="col-lg-1 col-md-1 col-s-1 col-xs-1">
          <h5 id="header" class="text-center">Followers</h5>
          <p id="header" class="text-center">
            <% @user = User.find(params[:id]) %>
            <% @users = [] %>

            <% User.all.each do |user| %>
              <% if user.following.include?(@user.id) %>
                <% @users.push(user) %>
                <% end %>
            <% end %>
            <%= @users.count %>
          </p>
        </div>
        <div class="text-right">
          <a>
            <% if current_user.following.include?(@user.id) %>
            <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary", id: "unfollow_btn" %>
            <% elsif current_user.id != @user.id %>
            <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
            <% end %>
          </a>
        </div>
      </div>



      <div class="container-fluid">
        <div class="row">

          <div class="container col-lg-3 col-md-3 col-sm-3 col-xs-3">
            <div id="showprofile">
              <h4><%= @user.name %></h4>
              <h6>@<%= @user.username %></h6>
              <p>
                <%= @user.bio %>
              </p>
              <p><span class="glyphicon glyphicon-map-marker"></span> <%= @user.location %></p>
              <p><span class="glyphicon glyphicon-calendar"></span> Joined <%= @user.created_at.strftime('%b %d %Y') %></p>
              <a id="tweetbtn" href="#" class="btn btn-primary">Tweet at <%= @user.name %></a>
            </div>
            <div>
              <h4>Followers:</h4>
              <%= render 'user_list' %>
            </div>
          </div>

          <div class="container col-xs-9 col-sm-9 col-md-9 col-lg-9">
            <ul class="list-group">
              <%= render @user.tweets.reverse %>
            </ul>
          </div>
        </div>
      </div>

app/views/epicenter/tag_tweets.html.erb
<h1>showing tweets for <%=@tag.phrase %></h1>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTalentTwitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "All Users", all_users_path %></li>
          <li><% if user_signed_in? %>
            <%= link_to "Followers", followers_path(id: current_user.id) %>
            <% end %></li>
          <li><% if user_signed_in? %>
            <%= link_to "Following", following_path(id: current_user.id) %>
          <% end %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li class="dropdown">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <% if current_user.avatar.blank? == false %>
              <%= image_tag current_user.avatar.url, size:25, class: "user-pic-nav img-circle" %>
              <% end %>
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <div class="navbar-login">
                  <li class="text-center"><strong><%= current_user.name %></strong></li>
                  <li class="text-center small">@<%= current_user.username %></li>
                  <li class="divider"></li>
                  <li class="text-center"><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li class="text-center"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
                </div>
              </ul>
            </li>
            <% end %>
            <%= link_to "Tweet", new_tweet_path(id: current_user.id), class:"btn btn-primary", id:"tweetbtn" %>
          </ul>
        </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message.html_safe %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :message, placeholder: "What's Happening?", id: :tweet_message, class:"form-control", rows:"2" %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group text-right">
    <%= form.submit "Tweet", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="media">
  <li class="list-group-item">
    <div class="media-left">
      <%= image_tag tweet.user.avatar.url, class:"img-circle", height:"60px", width:"60px" %>
    </div>
    <div class="media-body">
      <p><strong>
        <%= link_to tweet.user.name, show_user_path(id: tweet.user.id) %></strong>
        <small>@<%= tweet.user.username %> <%=tweet.created_at.strftime('%b %d %Y') %></small></p>
        <p><%= tweet.message.html_safe %></p>
      </div>
    </li>
  </div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>



  <div class="container col-xs-6">
    <% @tweets.each do |tweet| %>
        <h5><%= tweet.user.name %></h5>
        <p><%= tweet.message %></p>
        <!--
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->

    <% end %>
  </div>


<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user_id %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>